### PR TITLE
Update lwa4d.urdf.xacro

### PR DESCRIPTION
**Pull request by thiagodefreitas**
According to HW limits

### CODE REVIEW

**Comment by thiagodefreitas** [comment]
This is different from https://github.com/ipa320/schunk_modular_robotics/pull/121, as here the limits are really wrong according to the firmware limits

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by floweisshardt** [comment]
@thiagodefreitas please adjust for lwa4p and lwa4p_extended too.

**Comment by floweisshardt** [comment]
please merge with ipa320 first

**Comment by thiagodefreitas** [comment]
@ipa-fmw: Done

**Comment by floweisshardt** [comment]
merge after https://github.com/ipa320/schunk_modular_robotics/pull/124 (if still possible)

**Comment by thiagodefreitas** [comment]
@ipa-fmw The merge after https://github.com/ipa320/schunk_modular_robotics/pull/124 should work now

**Comment by floweisshardt** [comment]
@thiagodefreitas: please use the same `safety_offset` parameter for the limit calculation for lwa4d and lwa4p as it is done in #121 for lwa4p_extended

**Comment by thiagodefreitas** [comment]
@ipa-fmw, @ipa-nhg Updated if https://github.com/ipa320/schunk_modular_robotics/pull/121 is merged.

**Pull request merged**
