### PR TITLE
new urdf structure

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by NadiaHG** [comment]
merge with: https://github.com/ipa320/schunk_robots/pull/40 and https://github.com/ipa320/cob_robots/pull/264

**Comment by fmessmer** [comment]
LGTM
I assume the changes do not affect any transformations for the cob's...
The only thing that needs to be done now is to properly model the podests of the schunk arms (i.e. meshes for visual and collision tags of the podest_link) - if this is required...

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by floweisshardt** [comment]
tested in simulation: OK

**Pull request merged**
