### PR TITLE
fix lwa4d urdf - joint orientation according to convention

### PR DESCRIPTION
**Pull request by fmessmer**
- fixed motor orientation with Schunk MTS
  - adjusted joint orientation in URDF
  - fix orientation in meshes
  
  Now both hardware and software (motors and urdf) use the convention that +z-axis points towards the next joint!

### CODE REVIEW

**Comment by NadiaHG** [comment]
This pull request should be tested on a cob3, or at least communicate the cob3 developers that they should not update their repository before check with MTS the motor orientations.

**Comment by fmessmer** [comment]
This PR only affects cob3-9, In simulation it looks like this:
cob3-9_gazebo
cob3-9

Seems like the mounting position of the arm needs to be adjusted:
https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_hardware_config/cob3-9/urdf/calibration_default.urdf.xacro#L58-L63

Also, the default_arm_configs need to be checked:
https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_default_robot_config/cob3-9/arm_joint_configurations.yaml

**Comment by NadiaHG** [comment]
Updated and tested on cob3-9. 
Please merge together with this pull request  the cob_robots changes: https://github.com/ipa320/cob_robots/pull/343

**Comment by floweisshardt** [comment]
LGTM

**Pull request merged**
