### PR TITLE
use license apache 2.0

### PR DESCRIPTION
**Pull request by fmessmer**
external contributors:
@andreeatulbure 
@destogl 
@wxmerkt 
@frederikhegger 
@guihomework 
@LucaLattanzi 
@Will-McMahan 
@brsu-student 
@jsanch2s 
@svenschneider 
you have been contributing to this repository and are asked to express any concerns until August, 4th 2017 regarding changing the license of your contribution to Apache 2.0 

do not merge before: **August, 4th 2017**
merge together with other `use license apache 2.0` PRs

### CODE REVIEW

**Comment by wxmerkt** [comment]
LGTM 👍

**Comment by fmessmer** [comment]
@ipa-mig @ipa-fmw 
please confirm that the license changes in this repo are correct!
in particular `libmp5api`, `schunk_sdh` and `schunk_powercube_chain`

**Review by mgruhler — DISMISSED** [review]
- `lib5ampi` ~~is not correct. The copyright holder is Schunk, so we cannot just change this (copyright holder and license)! Also, the new header has just been copied below the old one. So this is adding another license and this is IMO incompatibel!~~  Fixed :+1: 
- `powercube_chain`: :+1:
- `schunk_sdh`:
    - ~~the files in `common` seem to be not licensed specifically. however, the copyright holder is also schunk. So not easy to change, and the copyright holder cannot be changed!~~ Fixed :+1: 
    - files in `ros`: :+1:

**Comment by floweisshardt** [comment]
- ```schunk_libm5api```: please keep ogininal headers with Copyright (even if there is no license mentioned). We should set the package.xml to APL2.0
- ```schunk_sdh```: we should keep all original headers in ```include``` but fill APL2.0 in all Files in the ```src``` directory. We should set the package.xml to APL2.0

**Comment by svenschneider** [comment]
Fine with me!

**Comment by fmessmer** [comment]
Schunk license headers back in place...I kept LGPL for `schunk_libm5api` as Schunk's license clearly states it...Apache2.0 for all the rest...

**Comment by destogl** [comment]
Agree.

**Comment by mgruhler** [comment]
:+1:

**Pull request merged**
