### PR TITLE
Non-penetrating and simplified collision objects

### PR DESCRIPTION
**Pull request by guihomework**
This solves issue #172 and provides simplified meshes for collision purposes.
- palm was reduced with blender decimate + manual closing unnecessary holes  (tri reduced from 914 to 192)
  sdh_palm_comparison_overlay
- knuckle tri was redrawn with simpler shapes around the original except penetrating part (tri reduced from 916 to 452)
  sdh_knuckle_comparison_overlay

fingers were not changed to keep the nice bumper collisions models and extract contacts exactly at the sensing pads.

### CODE REVIEW

**Review by fmessmer — CHANGES_REQUESTED** [review]
I can't recall having such "explosion" problems....but I haven't used an sdh in a while...

However, why do you use ```knuckle_collision.stl``` only for finger1 and __not__ for finger2 and thumb?
In case you do not have the "explosion" when just using it for finger1, the reason for the explosion but be something different...

**Comment by guihomework** [comment]
I might have missed the other knuckles when changing the collision.
I will double check with the latest version of the sdh (with simplified transmission and such). 
If I remember well the problem came when I instantiated gazebo_ros_control plugin for the sdh.

**Comment by guihomework** [comment]
@ipa-fxm Please have a look at my comment in #172 and I can add that indeed I had not added the other knuckle mainly because gazebo 2.2.3 behaves strangely when I added them. 
I started 10 times my simulation with the same setting, same urdf, and sometime it exploded completely (full arm compacted at 0,0,0), sometime the sdh was exploding permanently as on the picture in the issue, sometimes it was fine. So I suppose there is something more complex happening, maybe race conditions or such in the gazebo_ros_control plugin.
since in gazebo 7 in kinetic this issue does not occur, I don't need this fix anymore because we switched to kinetic. You can decide. 
I will push a fix to include the two other knuckles too as it makes sense to have them all updated in case you want that PR.

**Review by fmessmer — APPROVED** [review]

**Comment by fmessmer** [comment]
I can merge this as it does not harm...

**Pull request merged**
