### PR TITLE
properly link and install SDHLibrary

### PR DESCRIPTION
**Pull request by mathias-luedtke**

### CODE REVIEW

**Comment by ipa-mdl** [comment]
please sqash-merge.

**Comment by mathias-luedtke** [comment]
The release it broken: the executables got linked against the source library.
This fix does not work either since now they got linked against the devel library.
However, it does not touch the src anymore :)

**Comment by mathias-luedtke** [comment]
should work now.
devel space needs the lib from the source space to be present.

**Review by fmessmer — APPROVED** [review]
Thanks!
Will merge and rebase #184

**Pull request merged**
