### PR TITLE
Updated lwa4p urdf with manufacturer's specified joint limits.

### PR DESCRIPTION
**Pull request by Will-McMahan**
Addresses Issue #158

### CODE REVIEW

**Comment by fmessmer** [comment]
why is arm_3_joint the only joint with a lower limit? is this correct?

what about the velocity limits? are they correct? 

@athackst aren't you using a lwa4p? would you like to comment?

**Comment by Will-McMahan** [comment]
As noted in Issue #158, the joint limits are from http://mobile.schunk-microsite.com/fileadmin/user_upload/broshures/SCHUNK_Technical_data_LWA4P.pdf.  Joint 3 is the elbow bend joint, so it probably needs to be limited further to prevent robot self-collision.

I did not update the velocity limits, because the data sheet lists them as "Speed with nominal load".  So I don't think there is anything in the robot firmware that enforces this limit.

**Comment by fmessmer** [comment]
fixes #158

**Comment by athackst** [comment]
We are using the lwa4p.  These joint limits look ok to me.  I had to lower the velocity limits to spec as well.  I don't think that there is anything specifically enforcing a velocity limit, it's most likely effort/inertia  based, but 2 seemed too high for me when I ran it.

**Comment by fmessmer** [comment]
Thanks for the quick response.
Well, as the specs state the "speed with nominal load" to 72° (=1,26 [rad]), I'd say we should change this within this PR, as well

@athackst would you say this is a reasonable value?
@will2142 would you add the according changes to your PR?

(Unfortunately, we at IPA do not have a lwa4p hardware, so we rely on your feedback here)

**Comment by athackst** [comment]
Yes, 1.26 seemed reasonable to me.

**Comment by Will-McMahan** [comment]
Speed updated.

**Comment by fmessmer** [comment]
Thanks!

**Pull request merged**
