### PR TITLE
Older amtec modules

### PR DESCRIPTION
**Pull request by destogl**
The PowercubeCtrl is extended to support older Amtec modules. There is version checking added (look at second commit)

The code is tested against older and newer module.

### CODE REVIEW

**Comment by fmessmer** [comment]
please stick to the previous indentation scheme of the package....!

**Comment by destogl** [comment]
The thing is there is no clear scheme as far as I saw... One example for it is PowerCubeCtrl.cpp
 it is completely mixed (It is enough to look at Init method)....

What do you prefer tabs or spaces? I would than guess two spaces? Am I right?

**Comment by fmessmer** [comment]
Well, I don't know whether the indentation is consistent within this package or not...all I see is that indentation has been changed within a PR that proposes a new feature rather than styling...

Just saw that you have a particular commit for the conversion! This is perfect.
But even better would have been two separate PRs (one styling PR and one for the feature).
So, does the **whole** package now use spaces indentation consistently?
If not, could you please continue harmonizing indentation throughout the whole package?
(I don't have a particular preference....as long as it is not mixed...choose what is less effort!)

**Comment by destogl** [comment]
Ok I would than propose 4 spaces because this is python standard (PEP8) and also looks good with cpp.

No I just changed this two files, so this two files are consistent.

The whole package comes soon....

**Comment by wxmerkt** [comment]
schunk_sdh is formatted according to ROS format. E.g. I've formatted this package here: https://github.com/ipa320/schunk_modular_robotics/pull/149

Guidance:
- http://wiki.ros.org/CppStyleGuide

**Comment by destogl** [comment]
@iamwolf Thanks! I will format it than according to ROS

**Comment by wxmerkt** [comment]
I would use a bot user account to do the reformatting (since it will claim all changes to that user in GitHub) and run:
`find . -name '*.h' -or -name '*.hpp' -or -name '*.cpp' | xargs clang-format-3.6 -i -style=file $1`
I.e. set the GIT_AUTHOR to something like "SDH Format Bot" and then commit it from there

**Comment by destogl** [comment]
OK

**Comment by destogl** [comment]
Now only important part :)
Sorry for wanting to merge to much at once.

At the begin of the next will do reformatting.

**Comment by fmessmer** [comment]
Thanks for separating the feature....FR :ok:

**Pull request merged**
