### PR TITLE
Changed the origin of the left and right finger joints to avoid collision

### PR DESCRIPTION
**Pull request by crthilakraj**
- changed the origin of the left and right finger joints to avoid collision
- corrected the depricated hardware interface syntax in common.xacro file.

### CODE REVIEW

**Comment by christian-rauch** [comment]
Can you rebase your PR on `master` that contains https://github.com/ipa320/schunk_modular_robotics/pull/216?

**Comment by crthilakraj** [comment]
> Can you rebase your PR on `master` that contains #216?

Done!

**Comment by christian-rauch** [comment]
Thanks. Did you get these values +/-0.0055 from a datasheet or are they determined empirically?

**Comment by crthilakraj** [comment]
> /-0.0055 f
As per the URDF of pg70 ,  width of the finger is 0.01 and the lower limit for the joint is -0.001 hence the value 0.0055 , so that with in the range of joint limit there will be no collision between left and right finger joint.

**Comment by christian-rauch** [comment]
> > /-0.0055 f
> > As per the URDF of pg70 ,  width of the finger is 0.01 and the lower limit for the joint is -0.001 hence the value 0.0055 , so that with in the range of joint limit there will be no collision between left and right finger joint.

Can you reference a document from https://schunk.com/no_en/clamping-technology/series/pg/ that contains this information? I only found another URDF at https://github.com/SmartRoboticSystems/schunk_grippers/tree/master/schunk_pg70/urdf and it contains the same values.

I would like to document the change of the URDF because I do not have the physical PG 70 to verify the new values.

**Comment by crthilakraj** [comment]
i took the values from the urdf file from schunk description package. File name https://github.com/crthilakraj/schunk_modular_robotics/blob/indigo_dev/schunk_description/urdf/pg70/pg70.urdf.xacro. 
 <link name="${name}_finger_left_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
      <visual>
        <geometry>
          <box size="0.03 0.01 0.01"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="0.03 0.01 0.01"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </collision>
    </link>

**Comment by christian-rauch** [comment]
> i took the values from the urdf file from schunk description package. File name https://github.com/crthilakraj/schunk_modular_robotics/blob/indigo_dev/schunk_description/urdf/pg70/pg70.urdf.xacro.

The URDF file you are linking is part of this PR. What I am asking for is a secondary source or a way how you determined these values.
Are you referring to `<box size="0.03 0.01 0.01"/>`? Can you paste a screenshot of the gripper state with and without this change? I want to have this documented here, such that the change is reasonably justified.

**Comment by crthilakraj** [comment]
yes i am referring to the value mentioned `<box size="0.03 0.01 0.01"/>`
Following are the requested images.
1. with changes.
image
2. without change.
image.

As per urdf file origin of both finger_left_joint and finger_right_joint have same origin, hence there will be collison of the joints as shown in above image. Fom `<box size="0.03 0.01 0.01"/>` we know the collision geometry is l=0.03, w= 0.01, height=0.01. and from  `<limit effort="10" lower="-0.001" upper="0.0301" velocity="0.041"/>` the lower limit is -0.001. so to avoid collision,  i calculated the finger_xx_links origins y displacement ( 0.01 + 0.001)/2 .

**Comment by christian-rauch** [comment]
@crthilakraj Thanks for the clarification. I thought that we might need to change the joint limits instead of the joint origin, but your images show that the bracket is actually wrongly positioned.

**Pull request merged**
