### PR TITLE
fix model + use real inertias

### PR DESCRIPTION
**Pull request by fmessmer**
- fix lwa4p_extended model (i.e. add PRL module and mesh orientation)
- use real inertias for the links (calculated from CAD)

### CODE REVIEW

**Comment by floweisshardt** [comment]
visual review: OK
@ipa-fxm I assume you got the new limits (vel and pos) from the datasheet.
@ipa-nhg can you please test in simulation?

**Comment by NadiaHG** [comment]
@ipa-fxm why are you using new stl files instead of collada?

**Comment by fmessmer** [comment]
this PR should be accepted as it introduces the correct kinematics of the lwa4p_extended (including the PRL module alias arm_base_link) as well as realistic inertias...

The modified stl files were mainly introduced because they had a missing scene in it which was the reason for MoveIt! to not consider them while collision checking!

We can use collada for visual, that's fine...the *_reduced.stl have less vertices and are used for collision only.

Note that arm_1_link still uses the stl as the dae has a wrong orientation see #98

**Comment by floweisshardt** [comment]
visual review: OK

still todo for @ipa-fxm: switch back to dae and rotate arm_1_link

**Pull request merged**
