### PR TITLE
Format according to roscpp style guide, in line with ipa320 setup guideline

### PR DESCRIPTION
**Pull request by wxmerkt**
This PR does not include functional changes. It reformats the Schunk SDH package according to the roscpp style guide, via the Eclipse ROScpp linting/formatting style guide [2], [3]. 
This is a follow up to the initial question in https://github.com/ipa320/cob_common/issues/169, after I've found the guideline in [1] and applied it to the SDH package in this PR. The intention is to reformat the package according to the roscpp style, so that future contributions can be easily linted before making a PR (we have modifications that we'd like to contribute back that would have a lot of whitespace/formatting edits otherwise).

Looking forward to hearing your feedback on this - and also very happy to know if you already have an automated formatting in place for this package that I might have overlooked.

Thanks,
Wolfgang

Links:
[1] https://github.com/ipa320/setup/blob/master/coding_introduction/CodingIntroduction.md#ros-coding-styles
[2] http://wiki.ros.org/CppStyleGuide
[3] http://wiki.ros.org/IDEs#Auto_Formatting

### CODE REVIEW

**Comment by fmessmer** [comment]
Thanks @iamwolf highly appreciated.
So `schunk_sdh` is now [roslint](http://wiki.ros.org/roslint) conform?
As I wrote in https://github.com/ipa320/cob_common/issues/169#issuecomment-142989026 we thought about using it, but haven't tackled it...
However, we could make `schunk_sdh` our first package and example...

**Comment by floweisshardt** [comment]
LGTM

**Comment by wxmerkt** [comment]
I continued work on this towards roslint compatibility - it is mostly compatible (apart from line length that I'd like to leave as-is until more updates are merged in, and specifying whose job a TODO item is)

roslint output after the updates (I am only linting the source files and not the header files):

```
####
#### Running command: "make cmake_check_build_system" in "/home/wxm/ipab-distro/ipab-ros-workspace/build"
####
####
#### Running command: "make roslint_schunk_sdh -j8 -l8" in "/home/wxm/ipab-distro/ipab-ros-workspace/build"
####
ros/src/sdh.cpp:160:  Single-argument constructors should be marked explicit.  [runtime/explicit] [5]
ros/src/sdh.cpp:205:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh.cpp:285:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
ros/src/sdh.cpp:336:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:337:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:338:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:339:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:340:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:341:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:342:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:344:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh.cpp:409:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
ros/src/sdh.cpp:651:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh.cpp:709:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh.cpp:729:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh.cpp:752:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
Done processing ros/src/sdh.cpp
Done processing ros/src/dsa_only.cpp
ros/src/sdh_only.cpp:155:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:194:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh_only.cpp:271:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
ros/src/sdh_only.cpp:322:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:323:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:324:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:325:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:326:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:327:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:328:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:330:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh_only.cpp:390:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
ros/src/sdh_only.cpp:605:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh_only.cpp:663:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
ros/src/sdh_only.cpp:683:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
ros/src/sdh_only.cpp:706:  Lines should very rarely be longer than 150 characters  [whitespace/line_length] [4]
Done processing ros/src/sdh_only.cpp
Total errors found: 32
```

This is down from >250 errors. Only non-formatting changes is changing C-style static cast to C++-style static cast, the rest is solely formatting.

**Comment by fmessmer** [comment]
Awesome! Thanks @iamwolf!

Was this mainly a manual process?
What did you use for (automatically) fix whitespacing?

I also vote for keeping line lenghts as they are.
Regarding the ToDo: we no longer actively support this package...thus, we can have that as is, too.

**Comment by wxmerkt** [comment]
@ipa-fxm For the whitespacing, I used the command listed on the roslint wiki:

```
find -regextype egrep -regex '.*\.[ch](pp)?$' -exec astyle '{}' --style=allman --indent=spaces=2 --pad-oper --unpad-paren --pad-header --convert-tabs \;
```

I followed this with the eclipse ROS formatting (which is the allman/bsd used in the above command with a few modifications). Getting the roslint errors down from >250 to the 32 was a manual process.

Also very happy to do whitespace formatting and adding roslint to some of the other packages in this repository in a separate/the same PR.

**Comment by fmessmer** [comment]
@iamwolf 
sorry for leaving this unattended for such a long time....merging now!

Feel free to go on sending roslint PRs for other packages too...much appreciated!

**Pull request merged**
