### PR TITLE
enforce sdh operation mode on init

### LINKED ISSUE #91: Velocity Operation Mode in schunk_sdh
we have here a Schunk Dexterous Hand that we are using with ROS. I'm using the hydro version of the schunk_sdh package. We are able to move the hand in position operation mode using the dashboard.
I tried to use the velocity operation mode, changing the parameter OperationMode to velocity (in the configuration file sdh.yaml of schunk_hardware_config package) and publishing the velocities to the topic /sdh_controller/set_velocities but in this way the sdh does not move. I used as joint names the ones in the sdh.yaml configuration file and rad/s as unit. Moreover I noticed that if I publish a negative velocity the sdh_controller node gives the error:

[ERROR]: An exception was caught: cSDHErrorInvalidParameter: Invalid target velocity value (-2.864789 not in range [0.000000..157.895000])

as if only positive velocities are admitted. Exploring a little bit the code I think the problem should be in the function SetAxisTargetVelocity(axes_,velocities_) of the SDHLibrary, but I can't understand what's wrong.

### PR DESCRIPTION
**Pull request by floweisshardt**
fixes #91

### CODE REVIEW

**Comment by floweisshardt** [comment]
still needs to be tested on HW before merge.

**Comment by NadiaHG** [comment]
Tested on cob3-3: OK

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by mathias-luedtke** [comment]
Velocity mode on start-up: OK

**Comment by floweisshardt** [comment]
fixes #91

**Pull request merged**
