### PR TITLE
lwad description without base

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by floweisshardt** [comment]
please use urdf include instead of copying the whole urdf

lwa4d should look like:

< include lwa4d_without_base.urdf/>
< link base_link/>
< macro lwa4d parent_link = base_link"/>

**Comment by NadiaHG** [comment]
has to be merged together with https://github.com/ipa320/cob_robots/pull/263

**Comment by floweisshardt** [comment]
visual review: OK

but do not merge before the same is done for the other arms.

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
